name: real_estate
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  blurrycontainer: ^2.1.0
  cupertino_icons: ^1.0.2
  flutter_animate: ^4.5.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.1
  lottie: ^3.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/Montserrat/Montserrat-Black.ttf
          weight: 900
        - asset: assets/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/Montserrat/Montserrat-Thin.ttf
          weight: 100

spider:
  # Generates unit tests to verify that the assets exists in assets directory
  generate_tests: true
  # Use this to remove vcs noise created by the `generated` comments in dart code
  no_comments: true
  # Exports all the generated file as the one library
  export: true
  # This allows you to import all the generated references with 1 single import!
  use_part_of: true
  # Generates a variable that contains a list of all asset values.
  use_references_list: false
  package: resources
  groups:
      # PNG
    - path: assets/images
      class_name: AppImages
      types: [.png, jpeg, jpg]

      # Animation
    - path: assets/json
      class_name: AppAnime
      types: [.json]